version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - PORT=3000
    command: npm start
    depends_on:
      - backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "9000:9000"
    environment:
      - SERVER_PORT=9000
      - DB_URL=mongodb://root:example@mongo:27017/
      - ACCESS_TOKEN_SECRET=xb3tim8rnIdoMMJfGNaqMxHX6zyWGBrR
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/