version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/server/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DB_URL= mongodb://root:example@mongo:27017/
    volumes:
      - ./backend/server:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/